on:
  push:
  pull_request:
jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: olivr/copybara-action@v1.2.3
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          access_token: ${{ secrets.GH_TOKEN }}
          sot_repo: martincousido/copy-bara-test-private
          destination_repo: martincousido/copy-bara-test-public
          push_include: "module-public/** module-2-public/** .github/workflows/copybara.yml"
          copybara_options: "--last-rev 0feed2c02e942dc77cb0015732e94f559e8480e1"
